version: '3.1'
services:
  redis:
    restart: always
    image: redis:5.0.2
    container_name: redis
    #network_mode: host
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - 6379:6379
    volumes:
      - ./data:/data:rw
      - ./etc:/etc/redis/:rw
    command: ["redis-server","/etc/redis/redis.conf"]