version: '3.3'
services:
  myframework:
    build: .
    image: framework
    depends_on: 
      - mysql
      - redis
    ports: 
      - "8080:8080"
  redis:
    image: redis
    restart: always
    hostname: redis
    container_name: redis
    privileged: true
    ports:
      - 6379:6379
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /home/redis/data:/data
      - /home/redis/conf/redis.conf:/etc/redis/redis.conf
      - /home/redis/logs:/logs
    command: ["redis-server","/etc/redis/redis.conf"]
  mysql:
    container_name: mysql
    restart: always
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - /home/mysql/conf:/etc/mysql/conf.d
      - /home/mysql/logs:/logs
      - /home/mysql/data:/var/lib/mysql
    command: [
          'mysqld',
          '--innodb-buffer-pool-size=80M',
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_unicode_ci',
          '--default-time-zone=+8:00',
          '--lower-case-table-names=1'
        ]
    environment:
      MYSQL_ROOT_PASSWORD: root
  nginx:
    image: nginx:1.17.8
    restart: always
    container_name: nginx
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/nginx/www:/usr/share/nginx/html
      - /home/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /home/nginx/logs:/var/log/nginx
      - /home/nginx/ssl:/cert
