version: "3.6"
services:
  nginx:
     image: nginx
     container_name: nginx-test
     ports:
       - "8081:80"
     depends_on:
       - redis-compose
     stdin_open: true
     tty: true
     privileged: true
     command: ['/bin/bash']
  redis-compose:
     image: redis
     container_name: redis444
     ports:
        - "6379:6379"
     stdin_open: true
     tty: true
     privileged: true
     command: ['/bin/bash']