version: '3.3'
services:
  myapp:
    build: .
    image: demo
    depends_on: 
      - redis
    ports: 
      - "8080:8080"
  redis:
    image: redis
    restart: always
    hostname: redis
    container_name: redis
    privileged: true
    ports:
      - 6379:6379
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /home/redis/data:/data
      - /home/redis/conf/redis.conf:/etc/redis/redis.conf
      - /home/redis/logs:/logs
    command: ["redis-server","/etc/redis/redis.conf"]